#!/usr/bin/env python3
"""
OCC Setup Wizard
================
Interactive setup script to configure data sources.
Run: python3 setup.py
"""

import os
import json
import sys

# Colors for terminal
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}  {text}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*60}{Colors.END}\n")

def print_success(text):
    print(f"{Colors.GREEN}✓ {text}{Colors.END}")

def print_warning(text):
    print(f"{Colors.YELLOW}! {text}{Colors.END}")

def print_error(text):
    print(f"{Colors.RED}✗ {text}{Colors.END}")

def print_info(text):
    print(f"{Colors.BLUE}  {text}{Colors.END}")

def ask_yes_no(question, default=True):
    """Ask a yes/no question"""
    default_str = "Y/n" if default else "y/N"
    while True:
        response = input(f"{question} [{default_str}]: ").strip().lower()
        if response == "":
            return default
        if response in ("y", "yes"):
            return True
        if response in ("n", "no"):
            return False
        print("Please enter 'y' or 'n'")

def ask_input(prompt, default="", password=False, required=False):
    """Ask for text input"""
    if default:
        display = f"{prompt} [{default}]: "
    else:
        display = f"{prompt}: "

    while True:
        if password:
            import getpass
            value = getpass.getpass(display)
        else:
            value = input(display).strip()

        if value == "" and default:
            return default
        if value == "" and required:
            print_error("This field is required")
            continue
        return value

def configure_source(name, display_name, fields):
    """Configure a single data source"""
    print(f"\n{Colors.BOLD}--- {display_name} ---{Colors.END}")

    enabled = ask_yes_no(f"Enable {display_name}?", default=False)

    if not enabled:
        print_info(f"{display_name} will use mock data")
        return {"enabled": False}

    config = {"enabled": True}

    for field in fields:
        field_name = field["name"]
        field_label = field.get("label", field_name)
        field_default = field.get("default", "")
        field_password = field.get("password", False)
        field_required = field.get("required", True)
        field_help = field.get("help", "")

        if field_help:
            print_info(field_help)

        value = ask_input(field_label, default=field_default, password=field_password, required=field_required)
        config[field_name] = value

    print_success(f"{display_name} configured")
    return config

def generate_env_file(config):
    """Generate .env file from config"""
    lines = [
        "# OCC Configuration",
        "# Generated by setup.py",
        "",
    ]

    # ServiceNow
    lines.append("# ServiceNow")
    lines.append(f"SNOW_ENABLED={'true' if config.get('servicenow', {}).get('enabled') else 'false'}")
    if config.get('servicenow', {}).get('enabled'):
        lines.append(f"SNOW_URL={config['servicenow'].get('url', '')}")
        lines.append(f"SNOW_USER={config['servicenow'].get('username', '')}")
        lines.append(f"SNOW_PASS={config['servicenow'].get('password', '')}")
    lines.append("")

    # BUMS
    lines.append("# BUMS")
    lines.append(f"BUMS_ENABLED={'true' if config.get('bums', {}).get('enabled') else 'false'}")
    if config.get('bums', {}).get('enabled'):
        lines.append(f"BUMS_URL={config['bums'].get('url', '')}")
        lines.append(f"BUMS_USER={config['bums'].get('username', '')}")
        lines.append(f"BUMS_PASS={config['bums'].get('password', '')}")
    lines.append("")

    # SolarWinds
    lines.append("# SolarWinds")
    lines.append(f"SOLARWINDS_ENABLED={'true' if config.get('solarwinds', {}).get('enabled') else 'false'}")
    if config.get('solarwinds', {}).get('enabled'):
        lines.append(f"SOLARWINDS_URL={config['solarwinds'].get('url', '')}")
        lines.append(f"SOLARWINDS_USER={config['solarwinds'].get('username', '')}")
        lines.append(f"SOLARWINDS_PASS={config['solarwinds'].get('password', '')}")
    lines.append("")

    # AAP
    lines.append("# AAP")
    lines.append(f"AAP_ENABLED={'true' if config.get('aap', {}).get('enabled') else 'false'}")
    if config.get('aap', {}).get('enabled'):
        lines.append(f"AAP_URL={config['aap'].get('url', '')}")
        lines.append(f"AAP_TOKEN={config['aap'].get('token', '')}")
    lines.append("")

    # Audit
    lines.append("# Audit")
    lines.append(f"AUDIT_ENABLED={'true' if config.get('audit', {}).get('enabled') else 'false'}")
    if config.get('audit', {}).get('enabled'):
        lines.append(f"AUDIT_URL={config['audit'].get('url', '')}")
        lines.append(f"AUDIT_USER={config['audit'].get('username', '')}")
        lines.append(f"AUDIT_PASS={config['audit'].get('password', '')}")
    lines.append("")

    # Tenable
    lines.append("# Tenable")
    lines.append(f"TENABLE_ENABLED={'true' if config.get('tenable', {}).get('enabled') else 'false'}")
    if config.get('tenable', {}).get('enabled'):
        lines.append(f"TENABLE_URL={config['tenable'].get('url', '')}")
        lines.append(f"TENABLE_ACCESS_KEY={config['tenable'].get('access_key', '')}")
        lines.append(f"TENABLE_SECRET_KEY={config['tenable'].get('secret_key', '')}")
    lines.append("")

    # SSL
    lines.append("# SSL Verification (set to true for production)")
    lines.append(f"VERIFY_SSL={'true' if config.get('verify_ssl') else 'false'}")

    return "\n".join(lines)

def generate_config_json(config):
    """Generate config.json for easy viewing"""
    # Create a safe version without passwords
    safe_config = {}
    for source, settings in config.items():
        if isinstance(settings, dict):
            safe_config[source] = {
                k: ("***" if "pass" in k.lower() or "secret" in k.lower() or "token" in k.lower() else v)
                for k, v in settings.items()
            }
        else:
            safe_config[source] = settings
    return json.dumps(safe_config, indent=2)

def main():
    print_header("OCC Setup Wizard")
    print("This wizard will help you configure your data sources.")
    print("Press Enter to accept default values shown in [brackets].")
    print("Passwords will be hidden as you type.")

    config = {}

    # ServiceNow
    config['servicenow'] = configure_source(
        'servicenow',
        'ServiceNow',
        [
            {"name": "url", "label": "API URL", "default": "https://your-instance.service-now.com/api/now/table/incident", "help": "Example: https://mycompany.service-now.com/api/now/table/incident"},
            {"name": "username", "label": "Username"},
            {"name": "password", "label": "Password", "password": True},
        ]
    )

    # BUMS
    config['bums'] = configure_source(
        'bums',
        'BUMS (Unix Monitoring)',
        [
            {"name": "url", "label": "URL", "default": "http://your-bums-server/status", "help": "The BUMS status page URL"},
            {"name": "username", "label": "Username", "required": False},
            {"name": "password", "label": "Password", "password": True, "required": False},
        ]
    )

    # SolarWinds
    config['solarwinds'] = configure_source(
        'solarwinds',
        'SolarWinds',
        [
            {"name": "url", "label": "API URL", "default": "https://your-solarwinds:17778/SolarWinds/InformationService/v3/Json/Query"},
            {"name": "username", "label": "Username"},
            {"name": "password", "label": "Password", "password": True},
        ]
    )

    # AAP
    config['aap'] = configure_source(
        'aap',
        'AAP (Ansible)',
        [
            {"name": "url", "label": "API URL", "default": "https://your-aap-server/api/v2/jobs/"},
            {"name": "token", "label": "API Token", "password": True, "help": "Bearer token for AAP API"},
        ]
    )

    # Audit
    config['audit'] = configure_source(
        'audit',
        'Audit Report',
        [
            {"name": "url", "label": "Report URL", "default": "http://your-audit-server/report"},
            {"name": "username", "label": "Username", "required": False},
            {"name": "password", "label": "Password", "password": True, "required": False},
        ]
    )

    # Tenable
    config['tenable'] = configure_source(
        'tenable',
        'Tenable',
        [
            {"name": "url", "label": "API URL", "default": "https://your-tenable-server/rest/analysis"},
            {"name": "access_key", "label": "Access Key", "password": True},
            {"name": "secret_key", "label": "Secret Key", "password": True},
        ]
    )

    # SSL
    print(f"\n{Colors.BOLD}--- SSL Configuration ---{Colors.END}")
    config['verify_ssl'] = ask_yes_no("Verify SSL certificates? (Set 'No' for self-signed certs)", default=False)

    # Summary
    print_header("Configuration Summary")

    enabled_count = sum(1 for k, v in config.items() if isinstance(v, dict) and v.get('enabled'))
    print(f"Enabled sources: {enabled_count}/6")
    print()

    for source in ['servicenow', 'bums', 'solarwinds', 'aap', 'audit', 'tenable']:
        status = "Enabled" if config.get(source, {}).get('enabled') else "Disabled (mock data)"
        if config.get(source, {}).get('enabled'):
            print_success(f"{source.upper()}: {status}")
        else:
            print_warning(f"{source.upper()}: {status}")

    # Save
    print()
    if ask_yes_no("Save this configuration?", default=True):
        script_dir = os.path.dirname(os.path.abspath(__file__))

        # Save .env
        env_path = os.path.join(script_dir, '.env')
        env_content = generate_env_file(config)
        with open(env_path, 'w') as f:
            f.write(env_content)
        print_success(f"Saved: {env_path}")

        # Save config.json (safe version)
        config_path = os.path.join(script_dir, 'config.json')
        config_content = generate_config_json(config)
        with open(config_path, 'w') as f:
            f.write(config_content)
        print_success(f"Saved: {config_path} (passwords hidden)")

        print_header("Next Steps")
        print("1. Test the configuration:")
        print(f"   {Colors.BLUE}source .env && python3 fetch_data.py{Colors.END}")
        print()
        print("2. Start the dashboard:")
        print(f"   {Colors.BLUE}./start.sh{Colors.END}")
        print()
        print("3. Open in browser:")
        print(f"   {Colors.BLUE}http://localhost:8080{Colors.END}")
        print()
        print("4. Set up cron for auto-refresh (optional):")
        print(f"   {Colors.BLUE}crontab -e{Colors.END}")
        print(f"   Add: */5 * * * * cd {script_dir} && source .env && python3 fetch_data.py >> fetch.log 2>&1")

    else:
        print_warning("Configuration not saved")

    print()

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nSetup cancelled.")
        sys.exit(1)
